We'll start by converting the provided table into a dictionary and then into a Pandas DataFrame.

In [1]:
import pandas as pd

data = {
    'EmployeeID': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    'Name': ['Sarah', 'Michael', 'Jennifer', 'David', 'Lisa', 'James', 'Emma', 'Robert', 'Sophia', 'William'],
    'Department': ['Engineering', 'Sales', 'Marketing', 'Engineering', 'HR', 'Sales', 'Engineering', 'Marketing', 'Sales', 'HR'],
    'Salary': [85000, 62000, 71000, 92000, 58000, 68000, 78000, 75000, 65000, 60000],
    'Performance Score': [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    'Years of Service': [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}

df = pd.DataFrame(data)
df.set_index('EmployeeID', inplace=False)
df

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
1,202,Michael,Sales,62000,3,3
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
4,205,Lisa,HR,58000,4,4
5,206,James,Sales,68000,4,6
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5
8,209,Sophia,Sales,65000,5,4
9,210,William,HR,60000,3,3

Selecting only the 'Name', 'Department', and 'Salary' columns.

In [2]:
df[['Name', 'Department', 'Salary']]

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

Using integer-location based indexing to find the employee at the 5th index

In [3]:
df.iloc[5]

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 5, dtype: object

Using label-based indexing to find the specific employee with ID 208.

In [4]:
df.loc[df['EmployeeID'] == 208]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
7         208  Robert  Marketing   75000                  4                 5

Displaying all employees who work in the Engineering department.

In [5]:
df[df['Department'] == 'Engineering']

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

Displaying all employees earning more than 70,000.

In [6]:
df[df['Salary'] > 70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

Using multiple conditions to find high performers in the Sales department.

In [7]:
df[(df['Department'] == 'Sales') & (df['Performance Score'] >= 4)]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

Sorting the list to see who the highest earners are.

In [8]:
df.sort_values(by='Salary', ascending=False).head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

Organizing the data by department first, then ranking by salary within those groups.

In [9]:
df.sort_values(by=['Department', 'Salary'], ascending=[True, False])

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3